---
# tasks file for cassandra_dba
- name: Ensure epel is available
  yum:
    name: epel-release
    state: present

- name: Ensure Linux utilities
  yum:
    name: "{{ linux_utilities }}"
    state: latest
